### ISSUE TITLE
Failed:  Aborted because VCPKGRS_DYNAMIC is not set

### ISSUE THREAD

**Issue by Swoorup** [mcgoo/vcpkg-rs#11]
Shouldn't vcpkg-rs automatically set to static/dynamic rather than requiring this env var to be set by default. Users just building this library as a dependency won't know to set this env var unless they dig through the the problem

I didn't figure out this was causing my build to fail since it was a nested dependency. And digging further revealed it is caused by this library. 

```
C:\Users\Swoorup.Joshi\Documents\git\vcpkg [master ≡]
λ  vcpkg_cli.exe probe sqlite3
Failed:  Aborted because VCPKGRS_DYNAMIC is not set
```

**Comment by mcgoo** [comment]
I agree that it would be much better to be able to automatically pick up libraries if they are available. The first version deployed did not require VCPKGRS_DYNAMIC to be set. Unfortunately, this breaks `cargo install` for anyone who has `vcpkg` installed/integrated for things like `openssl` but does not have the DLL directory in the path, which is how `vcpkg` is intended to be used.

You can build static binaries by setting `RUSTFLAGS=-Ctarget-feature=+crt-static` but of course that requires an environment variable to be set too.

I'd like a solution to make it automatically enabled without breaking `cargo install` for everyone.

**Comment by Swoorup** [comment]
Couldn't be the VCPKGRS_DYNAMIC=0 or static be the default. I think it is just the un-presence of the environment variable that is causing the error.

**Comment by mcgoo** [comment]
Sorry about the long delay. 

A static vcpkg triplet would be a great default if it were possible, but you have to make the RUSTFLAGS environment setting in order for it to be correct to link to it because it uses a static CRT. It is not correct to link a Rust program without `-Ctarget-feature=+crt-static` to the vcpkg `x64-windows-static` triplet because the CRT is static in the vcpkg tree code and the DLL version in the Rust code.

(VCPKGRS_DYNAMIC=0 doesn't do anything, by the way.)

**Comment by Swoorup** [comment]
Trying to build project linked to diesel with postgres. Do you know why it complains that it can't find `libpq.lib`

Compiler Output:
```
" "msimg32.lib" "ntdll.lib" "opengl32.lib" "secur32.lib" "setupapi.lib" "user32.lib" "winspool.lib" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'libpq.lib'


error: aborting due to previous error

error: Could not compile `Rust-webapp-starter`.
```

vcpkg.exe list
```
λ  .\vcpkg.exe list
libpq:x64-windows                                  9.6.1-5          The official database access API of postgresql
libpq:x86-windows                                  9.6.1-5          The official database access API of postgresql
openssl-windows:x64-windows                        1.0.2q           OpenSSL is an open source project that provides ...
openssl-windows:x86-windows                        1.0.2q           OpenSSL is an open source project that provides ...
openssl:x64-windows                                0                OpenSSL is an open source project that provides ...
openssl:x86-windows                                0                OpenSSL is an open source project that provides ...
sqlite3:x64-windows                                3.26.0           SQLite is a software library that implements a s...
sqlite3:x64-windows-static                         3.26.0           SQLite is a software library that implements a s...
sqlite3:x86-windows                                3.26.0           SQLite is a software library that implements a s...
sqlite3:x86-windows-static                         3.26.0           SQLite is a software library that implements a s...
```

vcpkg_cli probe libpq
```
vcpkg_cli.exe probe libpq
Found library libpq
Include paths:
  D:\Thirdparty\vcpkg\installed\x64-windows\include
Library paths:
  D:\Thirdparty\vcpkg\installed\x64-windows\lib
Runtime Library paths:
  D:\Thirdparty\vcpkg\installed\x64-windows\bin
Cargo metadata:
  cargo:rustc-link-search=native=D:\Thirdparty\vcpkg\installed\x64-windows\lib
  cargo:rustc-link-search=native=D:\Thirdparty\vcpkg\installed\x64-windows\bin
  cargo:rustc-link-lib=libpq
  cargo:rustc-link-lib=libeay32
  cargo:rustc-link-lib=ssleay32
Found DLLs:
  D:\Thirdparty\vcpkg\installed\x64-windows\bin\libpq.dll
  D:\Thirdparty\vcpkg\installed\x64-windows\bin\libeay32.dll
  D:\Thirdparty\vcpkg\installed\x64-windows\bin\ssleay32.dll
Found libs:
  D:\Thirdparty\vcpkg\installed\x64-windows\lib\libpq.lib
  D:\Thirdparty\vcpkg\installed\x64-windows\lib\libeay32.lib
  D:\Thirdparty\vcpkg\installed\x64-windows\lib\ssleay32.lib
```

**Comment by mcgoo** [comment]
This seems to work for me, assuming it's the rust-webapp-starter. It took me down the path of finding some other bugs in vcpkg-rs, notably that if there are different versions of a package installed in different architectures, vcpkg-rs will not find one correctly. Looking at what you posted, this is not what is causing your issue.

It's possible that a `cargo clean -p pq-sys` might be required if you installed libpq in vcpkg after building already.

Since this was so long ago, I'm going to close this, but feel free to reopen or open a new issue.

```
C:\Users\jim\src\rust>git clone https://github.com/yagince/rust-webapp-starter.git
Cloning into 'rust-webapp-starter'...
[...]
C:\Users\jim\src\rust>cd rust-webapp-starter
C:\Users\jim\src\rust\rust-webapp-starter>set VCPKG_ROOT=c:\users\jim\src\vcpkg
C:\Users\jim\src\rust\rust-webapp-starter>set VCPKGRS_DYNAMIC=1
C:\Users\jim\src\rust\rust-webapp-starter>
C:\Users\jim\src\rust\rust-webapp-starter>cargo build
  Downloaded actix-web v0.7.13
[...]
 Finished dev [unoptimized + debuginfo] target(s) in 2m 19s
```
