### ISSUE TITLE
Provide interface for collecting include paths so they can be used within `cc`.

### ISSUE THREAD

**Issue by crlf0710** [mcgoo/vcpkg-rs#13]
Hi, want to supply the include paths to `cc` when building a -sys crate. However it seems there's no way to do this?

**Comment by mcgoo** [comment]
Not at the moment - that's an important feature, for sure. I'll take a look at implementing it, unless you would like to?

**Comment by crlf0710** [comment]
Currently i can work around this by hard-coding the paths in `build.rs`, so it's not urgent in my use case.

And sorry I don't really have time to investigate on this at the moment.

**Comment by mcgoo** [comment]
Actually, if you do
```
let libs = vcpkg::Config::new().emit_includes(true).find_package("harfbuzz").unwrap();
```
`libs.include_paths` will contain the include paths. If you get a chance to test that could you let me know if it works for you?

It's not necessary for the above, but with `.emit_includes(true)` the include directories will be visible to crates that include the `-sys` crate via the `cargo:include=` mechanism. That should set the `DEP_XXXXXXX_INCLUDE` environment variable for crates that depend on the `-sys` crate.

**Comment by crlf0710** [comment]
Yes, i tested it. It seems the `include_paths` always points to the `vcpkg` include directory. Very near, but not exactly the path i wanted. for example `harfbuzz` library will give -I ".../include/harfbuzz" in Cflags while i can only get ".../include" this way.

**Comment by mcgoo** [comment]
I'm pretty sure that I'm expected to `#include <harfbuzz/hb.h>` on Ubuntu, and I definitely am with vcpkg in Visual Studio, and also on macOS when it's installed with `brew`. For harfbuzz, vcpkg just points to the include/ level.

That said, I looked around and there is a **lot** of code out there that does `#include <hb.h>`, but it doesn't work like that for me anywhere. I'm not aware of having to add include paths under `/usr/include` as in `-I/usr/include/harfbuzz` on a linux box to allow use of shorter include paths, but... maybe that is done sometimes?

There are few possibilities

1. vcpkg-rs should include the port name in the include path
2. the port file for the port you are using is putting the headers in the wrong place inside vcpkg
3. you could include the header as <port/header.h> in your code

I'd like to get it right if it needs to be changed. Is the port you are using something in the vcpkg tree? I'd like to take a look at it if it is. Thanks for your help.

**Comment by crlf0710** [comment]
Thank you for your apply! 

Actually I'm not aware what the "correct" design is, but i've uploaded my use case into my private fork of a project [here](https://github.com/crlf0710/tectonic/pull/1/).

Currently it works, just a little cumbersome. 

You can also see that i have to change the c source code a little to make the code compile, which is actually ok in this case, but sub optimal if the code need to sync with a stand-alone c project. 

And besides this, i find that i've added the vcpkg include dir multiple times - every library give exactly the same result. It doesn't actually hurt. But... maybe there's a better way?

**Comment by mcgoo** [comment]
Funny - I didn't realize that you were using harfbuzz! (I chose it to test against because it has a lot of dependencies.)

You can simplify it a bit with the latest version of vcpkg-rs like this: https://github.com/crlf0710/tectonic/pull/2. (Feel free to kill that PR when you have had a look.)

You could probably avoid having to change the includes in the source files by creating an `include_shims` dir and putting an `hb.h` and all of the others in there that just contain `#include <harfbuzz/hb.h>`. Then, only for things that need it you'd add it to the include.  (I tried your version on Linux and it works fine the new way on Ubuntu 19.04 at least.)

You could insert the includes one by one `if !include_paths.contains(...)` maybe?

**Comment by crlf0710** [comment]
> You could probably avoid having to change the includes in the source files by creating an `include_shims` dir and putting an `hb.h` and all of the others in there that just contain `#include <harfbuzz/hb.h>`.

> You could insert the includes one by one if !include_paths.contains(...) maybe?

Yes! that's a nice idea. Thank you! And maybe i can use a BTreeSet or HashSet to collect the paths.

I think i can close this issue now~ Thank you for your suggestions!
