### ISSUE TITLE
vcpkg can't seem to find any libraries

### ISSUE THREAD

**Issue by LaylConway** [mcgoo/vcpkg-rs#14]
I installed cairo like this:
```
vcpkg install cairo
```
And I'm trying to find it like this in my build.rs
```
vcpkg::find_package("cairo").unwrap();
```
However, it fails to find the library
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibNotFound("cairo")', src\libcore\result.rs:997:5
```
Similarly, vcpkg_cli can't find it either
```
> vcpkg_cli probe cairo
Failed:  Could not find library in Vcpkg tree cairo
```

I verified that it's in the vcpkg list, I'm not sure where the problem is.

**Comment by mcgoo** [comment]
Assuming you are using Rust x86_64-pc-windows-msvc, you probably need to `vcpkg install cairo:x64-windows`, and set VCPKGRS_DYNAMIC=1 in the environment. You also need to have VCPKG_ROOT pointing to the vcpkg installation.

If that doesn't help, let me know what you are building on (windows-msvc, macos and linux are now supported) and what version of the vcpkg crate cargo picked up.

**Comment by LaylConway** [comment]
Yes, it seems that vcpkg by default installs x86 packages, once I set it to default to x64 it worked.
... kinda feels like a weird default in 2019
