### ISSUE TITLE
New release(s)?

### ISSUE THREAD

**Issue by pkgw** [mcgoo/vcpkg-rs#30]
@waych @mcgoo Now that the latest PRs have been merged in, is it time to release things to Crates.io?

Side note: for my personal work I have been getting super enthusiastic about release automation with a custom workflow+tool that I've developed, called [Cranko](https://pkgw.github.io/cranko/). I would definitely not suggest trying to jump into using it for this project right now, but I am eager to spread the word because it's really transforming how I approach these matters.

**Comment by waych** [comment]
Turns out I just did this 😄 

I just cut and published as `0.2.12`. Sorry for not giving a heads up!

I'll take a look at Cranko.  I don't have any plans to do much in this crate so don't expect the need for automation here, but I'm a nerd for build systems and automation overall.

**Comment by pkgw** [comment]
No worries, thanks for taking the lead! I'll need to remind myself how the Tectonic CI system pulls down the code, but hopefully I'll be able to remove the build system hacks that worked around the dep-ordering issues now!
