### ISSUE TITLE
Include license and readme in crate source

### ISSUE THREAD

**Issue by remilauzier** [mcgoo/vcpkg-rs#33]
Hi.
Fedora would like to have the readme and all the license file in the crate source to be able to package them.
Thanks for your time.
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_documentation

**Comment by waych** [comment]
This should now be addressed in `0.2.14`.
