### ISSUE TITLE
Make it compatible with stable-x86_64-gnu rust toolchain + x64-mingw-dynamic vcpkg triplet ?

### ISSUE THREAD

**Issue by lepapareil** [mcgoo/vcpkg-rs#48]
Hi,

I am attempting ton compile a rust program using libxml2 crate that uses vcpkg::find_package function to check if lib sources are available in the system.

For now, using stable-x86_64-msvc rust toochain with vcpkg x64-windows triplet, all is working as expected.

The next step is trying to switch to the GNU world, using x86_64-pc-windows-gnu rust toolchain with vcpkg x64-mingw-dynamic triplet, but vcpkg::find_package fails.

Is there any planned work to make vcpkg-rs compatible with GNU mode ?

Thks for your work :).

**Comment by pkgw** [comment]
Can you please provide a few more specifics about the commands that you're running and the error message(s) that you're getting? I'm not sure but it's possible that this should already work with the right configuration.

**Comment by lepapareil** [comment]
You're right, I was not that much clear.

For now, it seems that I can manage this issue reading https://vcpkg.io/en/docs/users/mingw.html#mingw-native:~:text=Open%20pull%20requests-,Using,-Mingw%2Dw64%20natively.

And I alternatively switch to a full msys2/mingw64 libxml2 compilation, without using vcpkg anymore, and it works fine.

Sorry for the wast of time 👎🏻, I close this issue and will reopen it if needed 😄.

**Comment by micolous** [comment]
I've made an attempt to actually implement this in #52, because I'd really like to be able to cross-compile Windows binaries from a non-Windows host, and use vcpkg's libraries (because MSYS2's `pacman` isn't available to me).
