### ISSUE TITLE
Not working for me 

### ISSUE THREAD

**Issue by trsh** [mcgoo/vcpkg-rs#6]
I have run `vcpkg integrate install`, I have installed zlib on it.
I have set `rustflags = ["-Ctarget-feature=+crt-static"]`.

Getting 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibNotFound("zlib")', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I have no idea how to debug this and how do I get an running `vcpkg_cli` command for console.

**Comment by mcgoo** [comment]
If you are statically linking you will need either the x64-windows-static or x86-windows-static variant installed in vcpkg.

**Comment by trsh** [comment]
Yes, that was the problem.
